@startuml Logic Components

!theme mars

skinparam handwritten false
skinparam shadowing false
skinparam backgroundColor #FFFFF0

package Backend {
    class DatabaseHandler {
        - initDatabases
        + writeUser(User)
        + deleteUser(User.name)
        + updateUser(User)
        + userFinancialProfile(User)
        --Getters--
        + getUser: string
        + getUserMetadata: map[string, string]
        --Setters--
        + setName: void
        + setEmail: void
        + setPassword: void
    }

    struct User {
        + id: int
        + name: string
        + password: string
        + email: string
        + createdAt: Date
    }

    enum Categories {
        + CURRENT_ACCOUNT: string
        + SAVINGS_ACCOUNT: string
        + TERM_DEPOSIT: string
        + MONEY_MARKET: string
        + CREDIT_CARD: string
        + PERSONAL_LOANS: string
        + PERSONAL_INVESTMENTS: string
        + MORTGAGE: string
        + HIRE_PURCHASE: string
        + INSURANCE: string
        + MICRO_LOANS: string
        + OTHER: string
    }

    struct AccountOverview {
        + id: int
        + current_account: list[string]
        + saving_account: list[string]
        + term_deposit: string

    }

    class FinancialAnalysis {
        + setAccount(Categories, User): void
        + getAccountOverview(User) 
    }

    User --o DatabaseHandler
    Categories --* FinancialAnalysis
    Categories --o DatabaseHandler
    AccountOverview --* FinancialAnalysis
}

package Frontend {
    class Authentication {
        # initAuthenticationServices: void
        + register(User): bool
        + requestAccountDeletion: void
        --Getters--
        + getName: string
        + getEmail: string
        --Setters--
        + setName: void
        + setEmail: void
        + setPassword: void
    }

    class Utilities {
        + saveLocalStorage(): void
    }

    struct User {
        + id: int
        + name: string
        + password: string 
        + email: string
    }

    User o-- Authentication
}

@enduml