export enum Categories {
    CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
    SAVINGS_ACCOUNT = 'SAVINGS_ACCOUNT',
    TERM_DEPOSIT = 'TERM_DEPOSIT',
    MONEY_MARKET = 'MONEY_MARKET',
    CREDIT_CARD = 'CREDIT_CARD',
    PERSONAL_LOANS = 'PERSONAL_LOANS',
    PERSONAL_INVESTMENTS = 'PERSONAL_INVESTMENTS',
    MORTGAGE = 'MORTGAGE',
    HIRE_PURCHASE = 'HIRE_PURCHASE',
    INSURANCE = 'INSURANCE',
    MICRO_LOANS = 'MICRO_LOANS',
    OTHER = 'OTHER'
}